// Piece file names from https://ascii.rest/library.js (216 pieces).
// The gallery is a small set of those names. The finder uses the full list.

(function (root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  root.AsciiPieces = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  const NAMES = [
  "a0",
  "agentmail",
  "almalinux",
  "alpine-dawn",
  "alpine-linux",
  "analog-clock",
  "apple",
  "aquarium",
  "arch-linux",
  "aurora",
  "aurora-fjord",
  "autumn",
  "bar-chart",
  "big-text",
  "black-hole",
  "bonsai",
  "boot-log",
  "bouncing-balls",
  "box-frames",
  "butterfly",
  "c",
  "calendar",
  "campfire",
  "candle",
  "candlesticks",
  "cat",
  "centos",
  "cherry-blossom",
  "chladni",
  "clojure",
  "cloudflare",
  "coderabbit",
  "coffee",
  "collabute",
  "command-code",
  "contour-map",
  "cpp",
  "cpu-meters",
  "csharp",
  "css",
  "cube",
  "dart",
  "databuddy",
  "debian",
  "deep-reef",
  "deepin",
  "desert-night",
  "digital-clock",
  "dissolve",
  "dividers",
  "dna-helix",
  "donut",
  "doom-fire",
  "double-pendulum",
  "earth",
  "earthrise",
  "eclipse",
  "elementary-os",
  "elixir",
  "elm",
  "endeavouros",
  "epicycles",
  "equalizer",
  "erlang",
  "falling-sand",
  "fedora",
  "fern",
  "ferris-wheel",
  "file-tree",
  "fireflies",
  "fireworks",
  "flag",
  "flow-field",
  "form-controls",
  "fountain",
  "fox",
  "fractal-tree",
  "galaxy",
  "gauge",
  "gentoo",
  "glider-gun",
  "glitch",
  "glxgears",
  "go",
  "greptile",
  "gyroscope",
  "harmonograph",
  "haskell",
  "hawa-mahal",
  "heart",
  "heartbeat",
  "heatmap",
  "helium",
  "hilbert-curve",
  "hourglass",
  "html",
  "icosahedron",
  "java",
  "javascript",
  "jellyfish",
  "julia",
  "julia-set",
  "kali-linux",
  "keiki",
  "kite",
  "kotlin",
  "kyoto-dusk",
  "landscape",
  "langtons-ant",
  "lantern-lake",
  "lava-lamp",
  "lighthouse",
  "lightning",
  "linux-mint",
  "lorenz",
  "lua",
  "mandelbrot",
  "manjaro",
  "marine-drive",
  "marquee",
  "matrix-rain",
  "maze",
  "mintlify",
  "misty-forest",
  "mobius-strip",
  "moon-phases",
  "morse",
  "newtons-cradle",
  "night-coast",
  "nixos",
  "not-found",
  "ocaml",
  "ocean-sunset",
  "omarchy",
  "opensuse",
  "orchid",
  "owl",
  "pendulum-wave",
  "perl",
  "php",
  "planet",
  "planetscale",
  "plasma",
  "playstation",
  "plucked-string",
  "polar",
  "pond-ripples",
  "pop-os",
  "progress-bar",
  "python",
  "r",
  "radar",
  "rain",
  "reaction-diffusion",
  "red-hat",
  "rocket",
  "rocky-linux",
  "rotozoomer",
  "ruby",
  "rule-30",
  "ruled-mountains",
  "rust",
  "saptarishi",
  "scala",
  "scramble",
  "sea-swell",
  "sierpinski",
  "skeleton",
  "skyline",
  "smoke",
  "snake",
  "snowfall",
  "solar-system",
  "sparkline",
  "sparks",
  "spider",
  "spinners",
  "split-flap",
  "spring",
  "starfield",
  "starlings",
  "storm-plains",
  "sundial",
  "sunrise",
  "supabase",
  "supermemory",
  "svelte",
  "swift",
  "synthwave",
  "taj-dawn",
  "terminal",
  "tesseract",
  "three-body",
  "tokyo-rain",
  "torus-knot",
  "train",
  "tunnel",
  "tux",
  "tv-static",
  "twisted-ring",
  "typescript",
  "typewriter",
  "ubuntu",
  "uptime-bar",
  "varanasi-ghats",
  "vercel",
  "vinyl",
  "void-linux",
  "voronoi",
  "wave-interference",
  "wave-text",
  "whale",
  "wind",
  "windmill",
  "zig",
  "zorin-os"
];

  const GALLERY = [
  {
    "name": "donut",
    "title": "Donut",
    "group": "Shape"
  },
  {
    "name": "cube",
    "title": "Cube",
    "group": "Shape"
  },
  {
    "name": "cat",
    "title": "Cat",
    "group": "Creature"
  },
  {
    "name": "campfire",
    "title": "Campfire",
    "group": "Nature"
  },
  {
    "name": "double-pendulum",
    "title": "Double pendulum",
    "group": "Physics"
  },
  {
    "name": "matrix-rain",
    "title": "Matrix rain",
    "group": "Effect"
  },
  {
    "name": "lava-lamp",
    "title": "Lava lamp",
    "group": "Object"
  },
  {
    "name": "night-coast",
    "title": "Night coast",
    "group": "Scene"
  }
];

  function has(name) {
    return NAMES.indexOf(name) !== -1;
  }

  return { NAMES: NAMES, GALLERY: GALLERY, has: has };
});
